/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdditionalTimeSeriesProperties
 */
export interface AdditionalTimeSeriesProperties {
    /**
     * 
     * @type {string}
     * @memberof AdditionalTimeSeriesProperties
     */
    unitSymbol?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdditionalTimeSeriesProperties
     */
    quantityName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AdditionalTimeSeriesProperties
     */
    rangeHigh?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdditionalTimeSeriesProperties
     */
    rangeLow?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AdditionalTimeSeriesProperties
     */
    name?: string | null;
}

export function AdditionalTimeSeriesPropertiesFromJSON(json: any): AdditionalTimeSeriesProperties {
    return AdditionalTimeSeriesPropertiesFromJSONTyped(json, false);
}

export function AdditionalTimeSeriesPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdditionalTimeSeriesProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'unitSymbol': !exists(json, 'unitSymbol') ? undefined : json['unitSymbol'],
        'quantityName': !exists(json, 'quantityName') ? undefined : json['quantityName'],
        'rangeHigh': !exists(json, 'rangeHigh') ? undefined : json['rangeHigh'],
        'rangeLow': !exists(json, 'rangeLow') ? undefined : json['rangeLow'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function AdditionalTimeSeriesPropertiesToJSON(value?: AdditionalTimeSeriesProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'unitSymbol': value.unitSymbol,
        'quantityName': value.quantityName,
        'rangeHigh': value.rangeHigh,
        'rangeLow': value.rangeLow,
        'name': value.name,
    };
}

