/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigurationReference
 */
export interface ConfigurationReference {
    /**
     * 
     * @type {string}
     * @memberof ConfigurationReference
     */
    iD?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigurationReference
     */
    version?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ConfigurationReference
     */
    timeStamp?: Date;
}

export function ConfigurationReferenceFromJSON(json: any): ConfigurationReference {
    return ConfigurationReferenceFromJSONTyped(json, false);
}

export function ConfigurationReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationReference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iD': !exists(json, 'ID') ? undefined : json['ID'],
        'version': !exists(json, 'Version') ? undefined : json['Version'],
        'timeStamp': !exists(json, 'TimeStamp') ? undefined : (new Date(json['TimeStamp'])),
    };
}

export function ConfigurationReferenceToJSON(value?: ConfigurationReference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ID': value.iD,
        'Version': value.version,
        'TimeStamp': value.timeStamp === undefined ? undefined : (value.timeStamp.toISOString()),
    };
}

