/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Package,
    PackageFromJSON,
    PackageFromJSONTyped,
    PackageToJSON,
} from './Package';

/**
 * 
 * @export
 * @interface DataChannelListPackage
 */
export interface DataChannelListPackage {
    /**
     * 
     * @type {Package}
     * @memberof DataChannelListPackage
     */
    _package?: Package;
}

export function DataChannelListPackageFromJSON(json: any): DataChannelListPackage {
    return DataChannelListPackageFromJSONTyped(json, false);
}

export function DataChannelListPackageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataChannelListPackage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_package': !exists(json, 'Package') ? undefined : PackageFromJSON(json['Package']),
    };
}

export function DataChannelListPackageToJSON(value?: DataChannelListPackage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Package': PackageToJSON(value._package),
    };
}

