/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NameObject,
    NameObjectFromJSON,
    NameObjectFromJSONTyped,
    NameObjectToJSON,
} from './NameObject';

/**
 * 
 * @export
 * @interface DataChannelID
 */
export interface DataChannelID {
    /**
     * 
     * @type {string}
     * @memberof DataChannelID
     */
    localID?: string;
    /**
     * 
     * @type {string}
     * @memberof DataChannelID
     */
    shortID?: string | null;
    /**
     * 
     * @type {NameObject}
     * @memberof DataChannelID
     */
    nameObject?: NameObject;
}

export function DataChannelIDFromJSON(json: any): DataChannelID {
    return DataChannelIDFromJSONTyped(json, false);
}

export function DataChannelIDFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataChannelID {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'localID': !exists(json, 'LocalID') ? undefined : json['LocalID'],
        'shortID': !exists(json, 'ShortID') ? undefined : json['ShortID'],
        'nameObject': !exists(json, 'NameObject') ? undefined : NameObjectFromJSON(json['NameObject']),
    };
}

export function DataChannelIDToJSON(value?: DataChannelID | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'LocalID': value.localID,
        'ShortID': value.shortID,
        'NameObject': NameObjectToJSON(value.nameObject),
    };
}

