/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DataChannel,
    DataChannelFromJSON,
    DataChannelFromJSONTyped,
    DataChannelToJSON,
} from './DataChannel';

/**
 * 
 * @export
 * @interface DataChannelList
 */
export interface DataChannelList {
    /**
     * 
     * @type {Array<DataChannel>}
     * @memberof DataChannelList
     */
    dataChannel?: Array<DataChannel>;
}

export function DataChannelListFromJSON(json: any): DataChannelList {
    return DataChannelListFromJSONTyped(json, false);
}

export function DataChannelListFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataChannelList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dataChannel': !exists(json, 'DataChannel') ? undefined : ((json['DataChannel'] as Array<any>).map(DataChannelFromJSON)),
    };
}

export function DataChannelListToJSON(value?: DataChannelList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DataChannel': value.dataChannel === undefined ? undefined : ((value.dataChannel as Array<any>).map(DataChannelToJSON)),
    };
}

