/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DataChannelID,
    DataChannelIDFromJSON,
    DataChannelIDFromJSONTyped,
    DataChannelIDToJSON,
} from './DataChannelID';
import {
    Property,
    PropertyFromJSON,
    PropertyFromJSONTyped,
    PropertyToJSON,
} from './Property';

/**
 * 
 * @export
 * @interface DataChannel
 */
export interface DataChannel {
    /**
     * 
     * @type {DataChannelID}
     * @memberof DataChannel
     */
    dataChannelID?: DataChannelID;
    /**
     * 
     * @type {Property}
     * @memberof DataChannel
     */
    property?: Property;
}

export function DataChannelFromJSON(json: any): DataChannel {
    return DataChannelFromJSONTyped(json, false);
}

export function DataChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataChannel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dataChannelID': !exists(json, 'DataChannelID') ? undefined : DataChannelIDFromJSON(json['DataChannelID']),
        'property': !exists(json, 'Property') ? undefined : PropertyFromJSON(json['Property']),
    };
}

export function DataChannelToJSON(value?: DataChannel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DataChannelID': DataChannelIDToJSON(value.dataChannelID),
        'Property': PropertyToJSON(value.property),
    };
}

