/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeatureProps
 */
export interface FeatureProps {
    /**
     * 
     * @type {string}
     * @memberof FeatureProps
     */
    vesselId?: string;
    /**
     * 
     * @type {Date}
     * @memberof FeatureProps
     */
    timestamp?: Date;
}

export function FeaturePropsFromJSON(json: any): FeatureProps {
    return FeaturePropsFromJSONTyped(json, false);
}

export function FeaturePropsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureProps {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'vesselId': !exists(json, 'vesselId') ? undefined : json['vesselId'],
        'timestamp': !exists(json, 'timestamp') ? undefined : (new Date(json['timestamp'])),
    };
}

export function FeaturePropsToJSON(value?: FeatureProps | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'vesselId': value.vesselId,
        'timestamp': value.timestamp === undefined ? undefined : (value.timestamp.toISOString()),
    };
}

