/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConfigurationReference,
    ConfigurationReferenceFromJSON,
    ConfigurationReferenceFromJSONTyped,
    ConfigurationReferenceToJSON,
} from './ConfigurationReference';
import {
    VersionInformation,
    VersionInformationFromJSON,
    VersionInformationFromJSONTyped,
    VersionInformationToJSON,
} from './VersionInformation';

/**
 * 
 * @export
 * @interface Header
 */
export interface Header {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof Header
     */
    shipID?: string;
    /**
     * 
     * @type {ConfigurationReference}
     * @memberof Header
     */
    dataChannelListID?: ConfigurationReference;
    /**
     * 
     * @type {VersionInformation}
     * @memberof Header
     */
    versionInformation?: VersionInformation;
    /**
     * 
     * @type {string}
     * @memberof Header
     */
    author?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Header
     */
    dateCreated?: Date | null;
}

export function HeaderFromJSON(json: any): Header {
    return HeaderFromJSONTyped(json, false);
}

export function HeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Header {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'shipID': !exists(json, 'ShipID') ? undefined : json['ShipID'],
        'dataChannelListID': !exists(json, 'DataChannelListID') ? undefined : ConfigurationReferenceFromJSON(json['DataChannelListID']),
        'versionInformation': !exists(json, 'VersionInformation') ? undefined : VersionInformationFromJSON(json['VersionInformation']),
        'author': !exists(json, 'Author') ? undefined : json['Author'],
        'dateCreated': !exists(json, 'DateCreated') ? undefined : (json['DateCreated'] === null ? null : new Date(json['DateCreated'])),
    };
}

export function HeaderToJSON(value?: Header | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'ShipID': value.shipID,
        'DataChannelListID': ConfigurationReferenceToJSON(value.dataChannelListID),
        'VersionInformation': VersionInformationToJSON(value.versionInformation),
        'Author': value.author,
        'DateCreated': value.dateCreated === undefined ? undefined : (value.dateCreated === null ? null : value.dateCreated.toISOString()),
    };
}

