/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CRSType,
    CRSTypeFromJSON,
    CRSTypeFromJSONTyped,
    CRSTypeToJSON,
} from './CRSType';

/**
 * 
 * @export
 * @interface ICRSObject
 */
export interface ICRSObject {
    /**
     * 
     * @type {CRSType}
     * @memberof ICRSObject
     */
    type?: CRSType;
}

export function ICRSObjectFromJSON(json: any): ICRSObject {
    return ICRSObjectFromJSONTyped(json, false);
}

export function ICRSObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ICRSObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : CRSTypeFromJSON(json['type']),
    };
}

export function ICRSObjectToJSON(value?: ICRSObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': CRSTypeToJSON(value.type),
    };
}

