/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IPosition
 */
export interface IPosition {
    /**
     * 
     * @type {number}
     * @memberof IPosition
     */
    readonly altitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IPosition
     */
    readonly latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof IPosition
     */
    readonly longitude?: number;
}

export function IPositionFromJSON(json: any): IPosition {
    return IPositionFromJSONTyped(json, false);
}

export function IPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): IPosition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'altitude': !exists(json, 'altitude') ? undefined : json['altitude'],
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
    };
}

export function IPositionToJSON(value?: IPosition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

