/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NameObject
 */
export interface NameObject {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof NameObject
     */
    namingRule?: string;
}

export function NameObjectFromJSON(json: any): NameObject {
    return NameObjectFromJSONTyped(json, false);
}

export function NameObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): NameObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'namingRule': !exists(json, 'NamingRule') ? undefined : json['NamingRule'],
    };
}

export function NameObjectToJSON(value?: NameObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'NamingRule': value.namingRule,
    };
}

