/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DataChannelList,
    DataChannelListFromJSON,
    DataChannelListFromJSONTyped,
    DataChannelListToJSON,
} from './DataChannelList';
import {
    Header,
    HeaderFromJSON,
    HeaderFromJSONTyped,
    HeaderToJSON,
} from './Header';

/**
 * 
 * @export
 * @interface Package
 */
export interface Package {
    /**
     * 
     * @type {Header}
     * @memberof Package
     */
    header?: Header;
    /**
     * 
     * @type {DataChannelList}
     * @memberof Package
     */
    dataChannelList?: DataChannelList;
}

export function PackageFromJSON(json: any): Package {
    return PackageFromJSONTyped(json, false);
}

export function PackageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Package {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'header': !exists(json, 'Header') ? undefined : HeaderFromJSON(json['Header']),
        'dataChannelList': !exists(json, 'DataChannelList') ? undefined : DataChannelListFromJSON(json['DataChannelList']),
    };
}

export function PackageToJSON(value?: Package | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Header': HeaderToJSON(value.header),
        'DataChannelList': DataChannelListToJSON(value.dataChannelList),
    };
}

