/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SearchScope,
    SearchScopeFromJSON,
    SearchScopeFromJSONTyped,
    SearchScopeToJSON,
} from './SearchScope';

/**
 * 
 * @export
 * @interface SearchRequestDto
 */
export interface SearchRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SearchRequestDto
     */
    phrase?: string | null;
    /**
     * 
     * @type {SearchScope}
     * @memberof SearchRequestDto
     */
    scope?: SearchScope;
}

export function SearchRequestDtoFromJSON(json: any): SearchRequestDto {
    return SearchRequestDtoFromJSONTyped(json, false);
}

export function SearchRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'phrase': !exists(json, 'phrase') ? undefined : json['phrase'],
        'scope': !exists(json, 'scope') ? undefined : SearchScopeFromJSON(json['scope']),
    };
}

export function SearchRequestDtoToJSON(value?: SearchRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'phrase': value.phrase,
        'scope': SearchScopeToJSON(value.scope),
    };
}

