/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum SearchScope {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2
}

export function SearchScopeFromJSON(json: any): SearchScope {
    return SearchScopeFromJSONTyped(json, false);
}

export function SearchScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchScope {
    return json as SearchScope;
}

export function SearchScopeToJSON(value?: SearchScope | null): any {
    return value as any;
}

