/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeSeriesRequestDto
 */
export interface TimeSeriesRequestDto {
    /**
     * 
     * @type {string}
     * @memberof TimeSeriesRequestDto
     */
    localId?: string;
}

export function TimeSeriesRequestDtoFromJSON(json: any): TimeSeriesRequestDto {
    return TimeSeriesRequestDtoFromJSONTyped(json, false);
}

export function TimeSeriesRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeSeriesRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'localId': !exists(json, 'localId') ? undefined : json['localId'],
    };
}

export function TimeSeriesRequestDtoToJSON(value?: TimeSeriesRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'localId': value.localId,
    };
}

