/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Unit
 */
export interface Unit {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof Unit
     */
    unitSymbol?: string;
    /**
     * 
     * @type {string}
     * @memberof Unit
     */
    quantityName?: string | null;
}

export function UnitFromJSON(json: any): Unit {
    return UnitFromJSONTyped(json, false);
}

export function UnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): Unit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'unitSymbol': !exists(json, 'UnitSymbol') ? undefined : json['UnitSymbol'],
        'quantityName': !exists(json, 'QuantityName') ? undefined : json['QuantityName'],
    };
}

export function UnitToJSON(value?: Unit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'UnitSymbol': value.unitSymbol,
        'QuantityName': value.quantityName,
    };
}

