/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VersionInformation
 */
export interface VersionInformation {
    /**
     * 
     * @type {string}
     * @memberof VersionInformation
     */
    namingRule?: string;
    /**
     * 
     * @type {string}
     * @memberof VersionInformation
     */
    namingSchemeVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof VersionInformation
     */
    referenceURL?: string | null;
}

export function VersionInformationFromJSON(json: any): VersionInformation {
    return VersionInformationFromJSONTyped(json, false);
}

export function VersionInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'namingRule': !exists(json, 'NamingRule') ? undefined : json['NamingRule'],
        'namingSchemeVersion': !exists(json, 'NamingSchemeVersion') ? undefined : json['NamingSchemeVersion'],
        'referenceURL': !exists(json, 'ReferenceURL') ? undefined : json['ReferenceURL'],
    };
}

export function VersionInformationToJSON(value?: VersionInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamingRule': value.namingRule,
        'NamingSchemeVersion': value.namingSchemeVersion,
        'ReferenceURL': value.referenceURL,
    };
}

