/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum VisVersion {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}

export function VisVersionFromJSON(json: any): VisVersion {
    return VisVersionFromJSONTyped(json, false);
}

export function VisVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): VisVersion {
    return json as VisVersion;
}

export function VisVersionToJSON(value?: VisVersion | null): any {
    return value as any;
}

