version: "3"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
        container_name: vista-lab-elasticsearch
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
            - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
            - "9300:9300"
        healthcheck:
            test: curl -s http://vista-lab-elasticsearch:9200 >/dev/null || exit 1
            interval: 30s
            timeout: 10s
            retries: 5
    kibana:
        image: docker.elastic.co/kibana/kibana:8.3.3
        container_name: vista-lab-kibana
        environment:
            - xpack.security.enabled=false
        depends_on:
            elasticsearch:
                condition: service_healthy
        ports:
            - "5601:5601"
    broker:
        depends_on:
            - questdb
        container_name: vista-lab-broker
        restart: unless-stopped
        ports:
            - "5050:5050"
        build:
            context: .
            dockerfile: src/MqttBroker/Dockerfile
    questdb:
        image: questdb/questdb
        container_name: vista-lab-db
        restart: unless-stopped
        ports:
            - "8812:8812"
            - "9000:9000"
            - "9003:9003"
            - "9009:9009"
        environment:
            QDB_TELEMETRY_ENABLED: "false"
            QDB_PG_PASSWORD: "Password1"
            QDB_PG_USER: "sa"
            QDB_LOG_W_STDOUT_LEVEL: ERROR
            QDB_PG_SELECT_CACHE_ENABLED: "false"
    grafana:
        depends_on:
            - questdb
        container_name: vista-lab-grafana
        image: grafana/grafana-oss:9.0.7
        ports:
            - "3000:3000"
        volumes:
            - grafana-storage:/var/lib/grafana
            - ./.grafana/dashboards:/var/lib/grafana/dashboards
            - ./.grafana/provisioning:/etc/grafana/provisioning
        environment:
            user: admin
            password: admin
            QDB_PG_PASSWORD: "Password1"
            QDB_PG_USER: "sa"
volumes:
    grafana-storage:
