version: "3"

services:
    broker:
        depends_on:
            - questdb
        container_name: vista-lab-broker
        restart: unless-stopped
        ports:
            - "5050:5050"
        build:
            context: .
            dockerfile: src/MqttBroker/Dockerfile
    questdb:
        image: questdb/questdb
        container_name: vista-lab-db
        restart: unless-stopped
        ports:
            - "8812:8812"
            - "9000:9000"
            - "9003:9003"
        environment:
            QDB_TELEMETRY_ENABLED: "false"
            QDB_PG_PASSWORD: "Password1"
            QDB_PG_USER: "sa"
            QDB_LOG_W_STDOUT_LEVEL: ERROR
