version: "3"

services:
    # APIs
    ingest-api:
        depends_on:
            - broker
        container_name: vista-lab-ingestapi
        restart: unless-stopped
        ports:
            - "5051:5051"
        build:
            context: .
            dockerfile: src/IngestApi/Dockerfile
        environment:
            BROKER_SERVER: "vista-lab-broker"
            DB_HOST: "vista-lab-db:9000"
    query-api:
        container_name: vista-lab-queryapi
        restart: unless-stopped
        ports:
            - "5052:5052"
        build:
            context: .
            dockerfile: src/QueryApi/Dockerfile
        environment:
            DB_HOST: "vista-lab-db:9000"
    # MQTT Services
    alert-manager:
        depends_on:
            - broker
        container_name: vista-lab-alert-manager
        restart: unless-stopped
        build:
            context: .
            dockerfile: src/AlertManager/Dockerfile
        environment:
            BROKER_SERVER: "vista-lab-broker"
    channel-streamer:
        depends_on:
            - broker
        container_name: vista-lab-channel-streamer
        restart: unless-stopped
        build:
            context: .
            dockerfile: src/ChannelStreamer/Dockerfile
        environment:
            BROKER_SERVER: "vista-lab-broker"
    simulator:
        depends_on:
            - ingest-api
            - broker
        container_name: vista-lab-simulator
        restart: unless-stopped
        build:
            context: .
            dockerfile: src/Simulator/Dockerfile
        environment:
            BROKER_SERVER: "vista-lab-broker"
    broker:
        depends_on:
            - questdb
        container_name: vista-lab-broker
        restart: unless-stopped
        ports:
            - "5050:5050"
        build:
            context: .
            dockerfile: src/MqttBroker/Dockerfile
    # Database
    questdb:
        image: questdb/questdb
        container_name: vista-lab-db
        restart: unless-stopped
        ports:
            - "8812:8812"
            - "9000:9000"
            - "9003:9003"
            - "9009:9009"
        environment:
            QDB_TELEMETRY_ENABLED: "false"
            QDB_PG_PASSWORD: "Password1"
            QDB_PG_USER: "sa"
            QDB_LOG_W_STDOUT_LEVEL: ERROR
