/* tslint:disable */
/* eslint-disable */
/**
 * VistaLab.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Vessel,
    VesselFromJSON,
    VesselToJSON,
} from '../models';

export interface QueryGetRequest {
    vessel?: string;
}

/**
 * 
 */
export class QueryApi extends runtime.BaseAPI {

    /**
     * Creates a vessel for the current user.
     */
    async queryGetRaw(requestParameters: QueryGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Vessel>> {
        const queryParameters: any = {};

        if (requestParameters.vessel !== undefined) {
            queryParameters['vessel'] = requestParameters.vessel;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/Query`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VesselFromJSON(jsonValue));
    }

    /**
     * Creates a vessel for the current user.
     */
    async queryGet(requestParameters: QueryGetRequest = {}, initOverrides?: RequestInit): Promise<Vessel> {
        const response = await this.queryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
