/* tslint:disable */
/* eslint-disable */
/**
 * QueryApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataChannelFilter
 */
export interface DataChannelFilter {
    /**
     * 
     * @type {Array<string>}
     * @memberof DataChannelFilter
     */
    primaryItem?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DataChannelFilter
     */
    secondaryItem?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DataChannelFilter
     */
    meta?: Array<string> | null;
}

export function DataChannelFilterFromJSON(json: any): DataChannelFilter {
    return DataChannelFilterFromJSONTyped(json, false);
}

export function DataChannelFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataChannelFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'primaryItem': !exists(json, 'primaryItem') ? undefined : json['primaryItem'],
        'secondaryItem': !exists(json, 'secondaryItem') ? undefined : json['secondaryItem'],
        'meta': !exists(json, 'meta') ? undefined : json['meta'],
    };
}

export function DataChannelFilterToJSON(value?: DataChannelFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'primaryItem': value.primaryItem,
        'secondaryItem': value.secondaryItem,
        'meta': value.meta,
    };
}

