/* tslint:disable */
/* eslint-disable */
/**
 * VistaLab.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Vessel
 */
export interface Vessel {
    /**
     * 
     * @type {string}
     * @memberof Vessel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Vessel
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof Vessel
     */
    imoNumber?: number;
}

export function VesselFromJSON(json: any): Vessel {
    return VesselFromJSONTyped(json, false);
}

export function VesselFromJSONTyped(json: any, ignoreDiscriminator: boolean): Vessel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'imoNumber': !exists(json, 'imoNumber') ? undefined : json['imoNumber'],
    };
}

export function VesselToJSON(value?: Vessel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'imoNumber': value.imoNumber,
    };
}

